### ISSUE TITLE
When Installed, and then open a terminal prompt and querying brew, it then tries to download ruby.

### ISSUE THREAD

**Issue by Oh4sh0** [pinnacol/macadmin#1]
It doesn't appear as though this completely installs brew. After running via a Self Service policy, and a user launches a terminal command, there is a prompt to install ruby, eg a brew update, brew upgrade, or brew doctor effectively seems to have to happen before the installation is complete. 

This was attempted on a macOS 14.3 device with Xcode CLT 15.1.

**Comment by fraserhess** [comment]
I considered running `brew update` as the current user at the end of the script but I couldn't determine if would run interactively. Therefore, I left that step to the first user interaction.

If you'd like to add it your implementation, I think it should be inserted at line 99 and look like:

```
sudo -u "${current_user}" "${homebrew_dir}/bin/brew" update
```
